dist: xenial
language: go
env:
- GO111MODULE=on
go:
- 1.12.x
git:
  depth: 1
install: true
notifications:
  email: false
script:
- "./scripts/ci_release.sh"
deploy:
  provider: releases
  api_key:
    secure: lumuh3rRx5Ya/iHPw9vGeYmEhhXSiiRaMMTlrnad40RAQdkuck1uTgXQs3j9TZ097XE+1eTvEqrK+6SRSAgSV37LgJnOi5pXeIz174tC1w3KjrGmG12J3WpB4e6c1ge8ngSM8oABY8qbipjCSP6WkFlu0DWoLyvuJ+WqfjgEhg/MzagFdd4UIokJ+5+ZupSk7dwdDXAc2iEfxKkCNOg+wzQsPR6cQzRuj8qwnTJnhFAnFmffwB09dv/V1D4/hctWfvG6iFOIvKVlXY+7ysEoXoPZe2MW2DkzvYskhoMvv4T5jf83MZLe8KQseCZSyBhbSadcrDRU8g/oO5nGu38yogRWFLpyCR80uFXhHWtDYqPHzF+Yvn6F8ezQtHpcefFK10v23TJ0HJIl7V9wpGUqTKfCoVs3U6Gl2UXeq15+QOQqrevsDdHAo8iw5RNfTfaQx+3dZ6iAs9JctmNr4kejhN+aqOKy0kTTk5dh+3y4yfJjpJ6hgh58B9vu6Ez2L9ZW+ZlDVylwmyosaMbgOeL736yIRbZHd2aTK7gvLCabBmtDayxSZ3kNnVv6eG0x0a39vq6PmskciJq1a2APu+llXPCicxlreF5Jm8S6QkzpCdeWhNAoByoklyQuqRLC5ioHm2b9fz44O+h4zZaWL9SBby+feXYTSefPRfmW2oj+xFo=
  file_glob: true
  file: scripts/build/*.gz
  draft: true
  skip_cleanup: true
  overwrite: true
  on:
    tags: true
